<a href="https://colab.research.google.com/github/Gattalraouf/Financial-Inclusion-In-Africa/blob/master/Financal_Inclusion_Africa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
from google.colab import drive

drive.mount('/content/gdrive')


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:

train_path = '/content/gdrive/My Drive/Colab Notebooks/DataSets/Financial Inclusion Africa/Train_v2.csv'
test_path='/content/gdrive/My Drive/Colab Notebooks/DataSets/Financial Inclusion Africa/Test_v2.csv'

In [0]:
train_data = pd.read_csv(train_path)
test_data = pd.read_csv(test_path)

In [0]:
np.shape(test_data)

(10086, 12)

In [0]:
train_data.head(5)

country  year  ...                  education_level                   job_type
0   Kenya  2018  ...              Secondary education              Self employed
1   Kenya  2018  ...              No formal education       Government Dependent
2   Kenya  2018  ...  Vocational/Specialised training              Self employed
3   Kenya  2018  ...                Primary education  Formally employed Private
4   Kenya  2018  ...                Primary education        Informally employed

[5 rows x 13 columns]

In [0]:
train_data.isnull().sum()

country                   0
year                      0
uniqueid                  0
bank_account              0
location_type             0
cellphone_access          0
household_size            0
age_of_respondent         0
gender_of_respondent      0
relationship_with_head    0
marital_status            0
education_level           0
job_type                  0
dtype: int64

In [0]:
# Changing indexes
data = train_data
variable_changes ={'Yes':1,'No':0,'Rural':0,'Urban':1, 'Male':0,'Female':1,
                   'Head of Household':0,'Spouse':1,'Child':2,'Parent':3,
                   'Other relative':4,'Other non-relatives':5,'Dont know':6,
                   'Married/Living together':0,'Divorced/Seperated':1,'Widowed':2, 
                   'Single/Never Married':3,'Don’t know':4,'No formal education':0, 
                   'Primary education':1,'Secondary education':2,'Vocational/Specialised training':3, 
                   'Tertiary education':4,'Other/Dont know/RTA':5,'Farming and Fishing':0,
                   'Self employed':1,'Formally employed Government':2,'Formally employed Private':3, 
                   'Informally employed':3,'Remittance Dependent':4,'Government Dependent':5, 
                   'Other Income':6,'No Income':7,'Dont Know/Refuse to answer':8,
                   'Rwanda':0,'Tanzania':1,'Kenya':2,'Uganda':3}
data =  data.replace(variable_changes)

In [0]:
data.isnull().sum()

country                   0
year                      0
uniqueid                  0
bank_account              0
location_type             0
cellphone_access          0
household_size            0
age_of_respondent         0
gender_of_respondent      0
relationship_with_head    0
marital_status            0
education_level           0
job_type                  0
dtype: int64

In [0]:
# droping the null value lines
new_data = data.dropna(axis = 0, how ='any')

In [0]:
new_data.head(5)

country  year    uniqueid  ...  marital_status  education_level  job_type
0        2  2018  uniqueid_1  ...               0                2         1
1        2  2018  uniqueid_2  ...               2                0         5
2        2  2018  uniqueid_3  ...               3                3         1
3        2  2018  uniqueid_4  ...               0                1         3
4        2  2018  uniqueid_5  ...               3                1         3

[5 rows x 13 columns]

In [0]:
np.shape(new_data)

(23524, 13)

In [0]:
# Divide the data to X & y
X = new_data.values[:, [0,1,4,5,6,7,8,9,10,11,12]]
y = new_data.values[:, 3]

In [0]:
X

array([[2, 2018, 0, ..., 0, 2, 1],
       [2, 2018, 0, ..., 2, 0, 5],
       [2, 2018, 1, ..., 3, 3, 1],
       ...,
       [3, 2018, 0, ..., 2, 1, 6],
       [3, 2018, 1, ..., 1, 2, 1],
       [3, 2018, 0, ..., 3, 2, 7]], dtype=object)

In [0]:
y

array([1, 0, 1, ..., 0, 0, 0], dtype=object)

In [0]:
y=y.astype('int')

In [0]:
y

array([1, 0, 1, ..., 0, 0, 0])

# Logistic Regression :

In [0]:
# Applying logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import train_test_split

# Create the model
model = LogisticRegression(solver="lbfgs")

# Train the model
model.fit(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
test_data.head(5)

country  year  ...                  education_level                      job_type
0   Kenya  2018  ...              Secondary education  Formally employed Government
1   Kenya  2018  ...  Vocational/Specialised training     Formally employed Private
2   Kenya  2018  ...              No formal education          Remittance Dependent
3   Kenya  2018  ...                Primary education          Remittance Dependent
4   Kenya  2018  ...              Secondary education          Remittance Dependent

[5 rows x 12 columns]

In [0]:
T_data = test_data
variable_changes ={'Yes':1,'No':0,'Rural':0,'Urban':1, 'Male':0,'Female':1,
                   'Head of Household':0,'Spouse':1,'Child':2,'Parent':3,
                   'Other relative':4,'Other non-relatives':5,'Dont know':6,
                   'Married/Living together':0,'Divorced/Seperated':1,'Widowed':2, 
                   'Single/Never Married':3,'Don’t know':4,'No formal education':0, 
                   'Primary education':1,'Secondary education':2,'Vocational/Specialised training':3, 
                   'Tertiary education':4,'Other/Dont know/RTA':5,'Farming and Fishing':0,
                   'Self employed':1,'Formally employed Government':2,'Formally employed Private':3, 
                   'Informally employed':3,'Remittance Dependent':4,'Government Dependent':5, 
                   'Other Income':6,'No Income':7,'Dont Know/Refuse to answer':8,
                   'Rwanda':0,'Tanzania':1,'Kenya':2,'Uganda':3}

T_data =  T_data.replace(variable_changes)


# Divide the data to X & y
X_test = T_data.values[:, [0,1,3,4,5,6,7,8,9,10,11]]

predicted_classes = model.predict(X_test)


In [0]:
np.shape(X_test)

(10086, 11)

In [0]:
np.shape(test_data)

(10086, 12)

In [0]:
csvData = [['uniqueid', 'bank_account']]
i=0
for x in predicted_classes:
  columnsData = test_data.loc[ : , ['uniqueid', 'country'] ]
  rowData = columnsData.loc[ i , : ]
  i=i+1
  csvData.append([rowData.uniqueid+' x '+rowData.country, x])

In [0]:
import csv

with open('/content/gdrive/My Drive/Colab Notebooks/DataSets/Financial Inclusion Africa/FIA_Submission.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(csvData)
csvFile.close()

# Wrapper Feature Selection : 

In [0]:
# Wrapper feature Selection 

# Import your necessary dependencies
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# Feature extraction
model_rfe = LogisticRegression(solver="lbfgs")
rfe = RFE(model_rfe, 
         1)


fit = rfe.fit(X, y)

print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


Taken Time :
1.668912649154663
Num Features: 1
Selected Features: [False False False  True False False False False False False False]
Feature Ranking: [ 7 10  4  1 11  8  5  3  6  2  9]


In [0]:
# Prédire les classes 
h = fit.predict(X_test)

In [0]:
csvData = [['uniqueid', 'bank_account']]
i=0
for x in predicted_classes:
  columnsData = test_data.loc[ : , ['uniqueid', 'country'] ]
  rowData = columnsData.loc[ i , : ]
  i=i+1
  csvData.append([rowData.uniqueid+' x '+rowData.country, x])

# Submission File Exporting

In [0]:
import csv

with open('/content/gdrive/My Drive/Colab Notebooks/DataSets/Financial Inclusion Africa/RFE_Submission.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(csvData)
csvFile.close()